### ISSUE TITLE
Не работает Java8

### ISSUE THREAD

**Issue by copterspace** [Antipat/python_minecraft#1]
Пытаюсь поставить ребёнку стек, описанный в книге: Python 3.11 + Сервер Spigot + Maincraft.
Maincraft официальный не продаётся, используем tlauncher.
Сервер Spigot из  https://disk.yandex.ru/d/he_W8RpxhfYYkw - наботает только с Java17 (https://disk.yandex.ru/d/sY1lAXRi0sxnrw)
Под Java 8 он отказывается стартовать.
При этом когда я снёс Java8 - у меня перестал запускаться tlauncher .
Python работет ок, с сервером контактирует.
Как правильно настроить стек  Java17 + tlauncher, чтоб запускался и Майнкрафт и сервер?
для tlauncher нужна Java8 (https://tlauncher.org/ru/install-java.html)

**Comment by Antipat** [comment]
Здравствуйте, посмотрите на это видео по Java17
https://youtu.be/Q_XaLyRQTNE
