### ISSUE TITLE
Привет!

### ISSUE THREAD

**Issue by katrudg** [Antipat/python_minecraft#2]
У меня в архиве нету папки Setting Up для spigot 12.2, при этом все работает. Зачем нужна эта папка? Я так понимаю мы с помощью спигота включаем локальный сервер на котором уже кем то создан мир?

**Comment by Antipat** [comment]
Здравтсвуйте. Только посетил страницу. 
Да, сам сервер spigot содержит ряд настроек по проектированию локации + сюда добавляется плагин RaspberryJuice, который лежит в папке с сервером. Он необходим для связи языка python с java командами в Minecraft.

Попутно там присутствует автосохранения и поэтому вы могли видеть и творение моих рук.
